# Étape 1 : Build de l'application React
FROM node:20-alpine as build
WORKDIR /app

# Installation des dépendances
COPY package*.json ./
RUN npm ci

# Copie du code et compilation
COPY . .
RUN npm run build

# Étape 2 : Serveur web Nginx pour servir les fichiers statiques
FROM nginx:alpine
# Copie des fichiers compilés depuis l'étape 1
COPY --from=build /app/dist /usr/share/nginx/html
# Copie de la configuration Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]